name: xray_companion
description: X-Ray companion app for e-skateboard with mock telemetry
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_blue_plus: ^1.16.5
  permission_handler: ^11.1.0
  provider: ^6.0.5
  drift: ^2.15.0
  drift_sqflite: ^2.3.0
  path_provider: ^2.1.2
  intl: ^0.19.0
  flutter_local_notifications: ^17.1.2
  sentry_flutter: ^7.19.0
  collection: ^1.18.0
  crypto: ^3.0.3
  cryptography: ^2.5.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  flutter_svg: ^2.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  test: ^1.24.0
flutter:
  uses-material-design: true
  assets:
    - ../assets/device-detail_definition.json
    - ../assets/deviceDetail.json
    - ../assets/kit_dependence/DeviceKit.json
    - ../assets/dynamic_config.json
    - ../assets/configList.json
    - ../assets/icons/
    - ../assets/images/
